EXECUTABLE = start
CXX = g++
LD := $(CXX)

SOURCES = $(wildcard src/*.cpp)
OBJECTS = $(patsubst %.cpp, %.o, $(SOURCES))
WRITTENFILES = $(wildcard *.dat)

TEST_EXECUTABLE 		:= $(EXECUTABLE)_tests

CXX_ERROR_WARNINGS_FLAG 	:= -Wall -Werror
CXX_INFORMATIONAL_WARNINGS_FLAG := -Wall
CXX_WARNDEPRECATE_FLAG 		:=
CXX_IMPORTPATH_FLAG 		:= -I
CXX_NOLINK_FLAG 		:= -c
CXX_OUTPUTFILE_FLAG 		:= -o
CXX_SYMBOLICDEBUGINFO_FLAG 	:= -g
CXX_INLINE_FLAG 		:= -finline-functions
CXX_OPTIMIZE_FLAG 		:= -O3 -fomit-frame-pointer
CXX_NOBOUNDSCHECK_FLAG 		:= -fno-bounds-check
#CXX_UNITTEST_FLAG 		:= -DTEST_RUN
CXX_RELEASE_FLAG 		:= -DRELEASE
CXX_DEBUG_FLAG 			:= -DDEBUG
#CXX_VERSION_FLAG :=
#CXX_NOOBJECT_FLAG :=
#CXX_STATIC_LIBRARY_FLAG := -static
#CXX_SHARED_LIBRARY_FLAG := -shared
#CXX_LINKER_FLAG := -Xlinker
#CXX_DOCFILE_FLAG := -fdoc-file=
#CXX_FPIC_FLAG := -fPIC
CXX_GTEST_LIB			:= #-pthread -lgtest #-lgtest_main
CXX_LINK_STDLIB			:= 
CXX_LINK_LIBMATH		:= -lm
CXX_ARCH_AMD64			:= -D_AMD64_CPU
CXX_ARCH_X86			:= -D_X86_CPU
CXX_STD_FLAG 			:= -std=c++11

CXXFLAGS := -Isrc/ $(CXX_STD_FLAG) $(CXX_INFORMATIONAL_WARNINGS_FLAG) $(CXX_WARNDEPRECATE_FLAG) $(CXX_SYMBOLICDEBUGINFO_FLAG) $(CXX_IMPORTPATH_FLAG)src/

#CXXFLAGS_RELEASE := $(CXX_OPTIMIZE_FLAG) $(CXX_INLINE_FLAG) $(CXX_RELEASE_FLAG) $(CXX_NOBOUNDSCHECK_FLAG)
#CXXFLAGS_DEBUG := $(CXX_DEBUG_FLAG)

CXXFLAGS_RELEASE := $(CXX_OPTIMIZE_FLAG) $(CXX_RELEASE_FLAG)
CXXFLAGS_DEBUG :=  $(CXX_DEBUG_FLAG)

LDFLAGS := $(CXX_LINK_STDLIB) $(CXX_LINK_LIBMATH)
LDFLAGS_TEST := $(LDFLAGS) $(CXX_GTEST_LIB)

BUILD ?= release
ifeq ($(BUILD), release)
	CXXFLAGS += $(CXXFLAGS_RELEASE)
endif
ifeq ($(BUILD), debug)
	CXXFLAGS += $(CXXFLAGS_DEBUG)
endif

.PHONY: all
all: build

.PHONY: build
build: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(LD) $(CXX_LINK_STDLIB) $(LDFLAGS) $^ $(CXX_OUTPUTFILE_FLAG)$@

OBJECTS_UNITTEST = $(patsubst %.o, %_unittest.o, $(OBJECTS))
%_unittest.o: %.cpp
	#$(CXX) $(CXXFLAGS) $(CXX_ARCH_DEF_FLAG) $(CXX_UNITTEST_FLAG) $(CXX_NOLINK_FLAG) $^ $(CXX_OUTPUTFILE_FLAG) $@
	$(CXX) $(CXXFLAGS) $(CXX_ARCH_DEF_FLAG) $(CXX_NOLINK_FLAG) $^ $(CXX_OUTPUTFILE_FLAG) $@

$(TEST_EXECUTABLE): $(OBJECTS_UNITTEST)
	$(LD) $(CXX_LINK_STDLIB) $(CXXFLAGS_DEBUG) $(LDFLAGS) $(LDFLAGS_TEST) $^ $(CXX_OUTPUTFILE_FLAG) $@

.PHONY: tests
tests: $(TEST_EXECUTABLE)
	./$(TEST_EXECUTABLE)

.PHONY: clean
clean:
	rm -rf $(EXECUTABLE) $(TEST_EXECUTABLE) $(OBJECTS) $(OBJECTS_UNITTEST) $(WRITTENFILES)
