#include "Tests_Sorting_Insertionsort.h"
#include "Tests_Sorting_Quicksort.h"
#include "Tests_Sorting_Quicksort1.h"
#include "Tests_Sorting_Quicksort2.h"
#include "Tests_Sorting_Quicksort3.h"
#include "Tests_Sorting_Mergesort.h"
#include "Tests_Sorting_Heapsort.h"
